// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGbtuk6FlOMGnTMS9PqQi8iFXuRoH-0M',
    appId: '1:859638991274:web:ddd24d06f8f16cabe843d3',
    messagingSenderId: '859638991274',
    projectId: 'capstone-416104',
    authDomain: 'capstone-416104.firebaseapp.com',
    storageBucket: 'capstone-416104.appspot.com',
    measurementId: 'G-CPYYVWJYCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMghO6NrbGgYm5Xb7TchS9NyFNA2pjMr4',
    appId: '1:859638991274:android:3cc6ffb166b99462e843d3',
    messagingSenderId: '859638991274',
    projectId: 'capstone-416104',
    storageBucket: 'capstone-416104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxa9nM6eKNLjf3o_3MeyNUWcrIsNTeHdc',
    appId: '1:859638991274:ios:d47bdcb2be14ea2ee843d3',
    messagingSenderId: '859638991274',
    projectId: 'capstone-416104',
    storageBucket: 'capstone-416104.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxa9nM6eKNLjf3o_3MeyNUWcrIsNTeHdc',
    appId: '1:859638991274:ios:93b6c860f7649fede843d3',
    messagingSenderId: '859638991274',
    projectId: 'capstone-416104',
    storageBucket: 'capstone-416104.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
